>>> add_integer = __import__('0-add_integer').add_integer
>>> add_integer(30, 4)
34
>>> add_integer(30, 4.8)
34
>>> add_integer(3.6, 4.8)
7.8
>>> add_integer(3.6, '4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 13, in add_integer
    return a+b
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> add_integer(3, '4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 12, in add_integer
    raise TypeError("b must be an integer")
TypeError: b must be an integer
>>> add_integer('3', '4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 10, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer
>>> add_integer('3', 4.3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 13, in add_integer
    return a+b
TypeError: can only concatenate str (not "int") to str
>>> add_integer('3', [4,3,2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 10, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer
>>> add_integer(3, [4,3,2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 12, in add_integer
    raise TypeError("b must be an integer")
TypeError: b must be an integer
>>> add_integer({1,2,3}, [4,3,2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 10, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer
>>> add_integer([1,2,3], [4,3,2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 10, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer
>>> add_integer(8)
106
>>> add_integer(8,)
106
>>> add_integer(8, -6)
2
>>> add_integer(-8, -6)
-14
>>> add_integer(-8, -6.4)
-14
>>> add_integer(-8.6, -6)
-14
>>> add_integer(-8.6, -6.5)
-14.5
>>> add_integer(8.6, 6.5)
14.5
>>> add_integer(8.6223, 6)
14
>>> add_integer(8.62237865, 6)
14
>>> add_integer(8.62237865, {x:2, y:3})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined
>>> add_integer(8.62237865, {'x':2, 'y':3})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 13, in add_integer
    return a+b
TypeError: unsupported operand type(s) for +: 'int' and 'dict'
>>> add_integer(8, {'x':2, 'y':3})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 12, in add_integer
    raise TypeError("b must be an integer")
TypeError: b must be an integer
>>> add_integer({2,3}, {'x':2, 'y':3})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 10, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer
>>> add_integer({'x':2, 'y':3}, 6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 10, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer

